version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.9"
  jobs:
    post_install:
      - pip install poetry
      # Install dependencies with dev dependencies group
      # https://python-poetry.org/docs/managing-dependencies/#dependency-groups
      - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH poetry install --with dev,optional

sphinx:
  configuration: doc/sphinx-docs/source/conf.py
