
class CaTabRaPaths:
    Config = 'config.json'
    TrainData = 'train_data.h5'
    TestData = 'test_data.h5'
    Statistics = 'statistics'
    Encoder = 'encoder.json'
    ModelSummary = 'model_summary.json'
    Model = 'model.joblib'
    TrainingHistory = 'training_history.xlsx'
    OODModel = 'ood.joblib'
    OODStats = 'ood.xlsx'
    ConsoleLogs = 'console.txt'
    Invocation = 'invocation.json'
    Predictions = 'predictions.xlsx'
