#  Copyright (c) 2022. RISC Software GmbH.
#  All rights reserved.

class CaTabRaPaths:
    """
    Data class defining file names of objects generated by CaTabRa
    """

    #: Configuration file as in core.paths.
    Config = 'config.json'

    #: Data used for training.
    TrainData = 'train_data.h5'

    #: History of the training as performance over time.
    TestData = 'test_data.h5'
    """ Data used for testing. """

    #: Data on which predictions were explained.
    ExplanationData = 'explanation_data.h5'

    #: Folder for descriptive statistics of data set.
    Statistics = 'statistics'

    #: Encoder parameters that can be loaded as Encoder object.
    Encoder = 'encoder.json'

    #: Summary of models created during training.
    ModelSummary = 'model_summary.json'

    #: The final (best) model from the training pipeline.
    Model = 'model.joblib'

    #: History of the training as performance over time.
    TrainingHistory = 'training_history.xlsx'

    #: Out-of-distribution detector generated during training.
    OODModel = 'ood.joblib'

    #: Probabilities and decisions of data being OOD,
    OODStats = 'ood.xlsx'

    #: Console output redirected to log file.
    ConsoleLogs = 'console.txt'

    #: Invocation file containing the parameters used in call.
    Invocation = 'invocation.json'

    #: Model decisions for a data set.
    Predictions = 'predictions.xlsx'

    #: Ensemble fitted during training.
    FittedEnsemble = 'fitted_ensemble.joblib'

    #: Versions of Python packages used on creation.
    Versions = 'versions.txt'
